"""MockMaterialClassifierService: deterministic fake material classifier for development.

Returns a reproducible MaterialDistribution seeded from the MD5 hash of the
image bytes — same image always returns same distribution, making pipeline
output predictable during testing.

Replace with MaterialClassifierService (YOLOv8s-cls) once the model is trained:
    class MaterialClassifierService:
        async def classify(self, image_bytes: bytes) -> MaterialDistribution: ...
No changes to pipeline_runner.py or analysis_orchestrator.py are needed when swapping.
"""
import hashlib
import random
from typing import List

from chatbot.utils.schemas import MATERIAL_CLASSES, MaterialDistribution, MaterialType


class MockMaterialClassifierService:
    """Fake material classifier that returns deterministic distribution for development.

    Same image bytes always produce the same distribution and dominant material,
    ensuring reproducible pipeline runs without a trained YOLOv8s-cls model.
    """

    async def classify(self, image_bytes: bytes) -> MaterialDistribution:
        """Return a deterministic material distribution for the given image.

        The distribution is generated by seeding the RNG with MD5(image_bytes),
        sampling 5 random scores, then normalising to sum to 1.0.

        Args:
            image_bytes: Raw image bytes (used only for seeding the RNG).

        Returns:
            MaterialDistribution with dominant material and confidence derived
            from the top probability.
        """
        seed = hashlib.md5(image_bytes).hexdigest()
        rng = random.Random(seed)
        raw_scores: List[float] = [rng.uniform(0.05, 1.0) for _ in MATERIAL_CLASSES]
        total = sum(raw_scores)
        distribution = {
            material: round(score / total, 4)
            for material, score in zip(MATERIAL_CLASSES, raw_scores)
        }
        dominant = max(distribution, key=lambda k: distribution[k])
        confidence = distribution[dominant]
        return MaterialDistribution(
            distribution=distribution,
            dominant=dominant,
            confidence=confidence,
        )
