"""Evaluation harness for the open-vocabulary architecture-style pipeline.

Runs the full pipeline (Agent A → KB grounding → panel → arbiter) over the
labelled 200-image benchmark and reports where the system actually loses:

    candidate_recall@K   ← is the ground-truth style even in the candidate set?
                            (the HARD CEILING set by Stage A/B; the panel can
                            never beat it — decision #76)
    top-1 / top-3        ← accuracy of the final mixture (Stage C–E)
    family accuracy      ← right family (parent), possibly wrong child style
    distractor rate      ← did the result fall for an injected decoy feature
                            (ev6–ev10 in the ground truth)?
    risk-coverage        ← top-1 accuracy vs coverage as the abstention
                            threshold on panel_agreement is swept

All style comparisons collapse synonyms to KB ids via ``StyleKbService.match``
so "Traditional Chinese" == "Chinese traditional", etc.

Dataset:
    docs/image_gen_ground_truth.csv  — prompt_id, main_style, ev1..ev10[_style]
    data/ChatGPT/{prompt_id}.png     — image generated by ChatGPT
    data/Gemini/{prompt_id}.png      — image generated by Gemini

Usage (from project root):
    python scripts/evaluate_openvocab.py                       # all 200 images
    python scripts/evaluate_openvocab.py --limit 10            # first 10 ids
    python scripts/evaluate_openvocab.py --generators gemini   # one generator
    python scripts/evaluate_openvocab.py --workers 4 --out results/base.csv

Results are written incrementally (one row per image, flushed as it completes),
so a run interrupted by a quota outage keeps its progress. Re-run the SAME
command with ``--resume`` to continue: already-scored images are skipped and only
the missing / previously-errored ones are analysed.

    python scripts/evaluate_openvocab.py --out results/run4.csv              # stops at image 90
    python scripts/evaluate_openvocab.py --out results/run4.csv --resume     # continues from 91

The pipeline requires GEMINI_API_KEY, DEEPSEEK_API_KEY and OPENAI_API_KEY in
``.env``. Bilingual translation is disabled during evaluation (it does not
affect any metric and saves two LLM calls per image).
"""
from __future__ import annotations

import argparse
import asyncio
import csv
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

# Make the project root importable when run as ``python scripts/...``.
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from app.config import settings  # noqa: E402
from chatbot.services.analysis_orchestrator import (  # noqa: E402
    AnalysisOrchestrator,
    is_pipeline_configured,
)
from chatbot.services.style_kb_service import get_style_kb  # noqa: E402
from chatbot.utils.schemas import FinalAnalysisResult  # noqa: E402

_GT_CSV = _PROJECT_ROOT / "docs" / "image_gen_ground_truth.csv"
_DATA_DIRS = {"chatgpt": _PROJECT_ROOT / "data" / "ChatGPT",
              "gemini": _PROJECT_ROOT / "data" / "Gemini"}
_RISK_THRESHOLDS = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]


@dataclass
class GroundTruth:
    """One row of the benchmark: the main style + the injected decoy styles."""

    prompt_id: str
    building_type: str
    main_style: str
    distractor_styles: List[str] = field(default_factory=list)


@dataclass
class EvalRow:
    """Per-image evaluation outcome."""

    prompt_id: str
    generator: str
    gt_style: str
    pred_style: str
    recall_hit: bool
    top1_hit: bool
    top3_hit: bool
    family_hit: bool
    distractor_hit: bool
    uncertain: bool
    panel_agreement: Optional[float]
    n_candidates: int
    error: str = ""
    group: str = ""  # diagnostic subset group: broken / hard / guard (else "")


_CSV_HEADER = [
    "prompt_id", "generator", "gt_style", "pred_style", "recall_hit",
    "top1_hit", "top3_hit", "family_hit", "distractor_hit", "uncertain",
    "panel_agreement", "n_candidates", "error", "group",
]


def _row_values(r: EvalRow) -> list:
    """Serialise an EvalRow to a CSV row (booleans as 0/1)."""
    return [
        r.prompt_id, r.generator, r.gt_style, r.pred_style,
        int(r.recall_hit), int(r.top1_hit), int(r.top3_hit),
        int(r.family_hit), int(r.distractor_hit), int(r.uncertain),
        r.panel_agreement, r.n_candidates, r.error, r.group,
    ]


def _read_existing_rows(path: Path) -> List[EvalRow]:
    """Read previously written rows back into EvalRow objects (for --resume)."""
    rows: List[EvalRow] = []
    with path.open(encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            agree = r.get("panel_agreement")
            rows.append(EvalRow(
                prompt_id=r["prompt_id"], generator=r["generator"],
                gt_style=r.get("gt_style", ""), pred_style=r.get("pred_style", ""),
                recall_hit=bool(int(r.get("recall_hit") or 0)),
                top1_hit=bool(int(r.get("top1_hit") or 0)),
                top3_hit=bool(int(r.get("top3_hit") or 0)),
                family_hit=bool(int(r.get("family_hit") or 0)),
                distractor_hit=bool(int(r.get("distractor_hit") or 0)),
                uncertain=bool(int(r.get("uncertain") or 0)),
                panel_agreement=(
                    float(agree) if agree not in (None, "", "None") else None),
                n_candidates=int(r.get("n_candidates") or 0),
                error=r.get("error") or "", group=r.get("group") or "",
            ))
    return rows


def _load_ground_truth() -> Dict[str, GroundTruth]:
    """Read the ground-truth CSV into prompt_id → GroundTruth."""
    rows: Dict[str, GroundTruth] = {}
    with _GT_CSV.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            distractors = [
                row[f"ev{i}_style"].strip()
                for i in range(6, 11)
                if row.get(f"ev{i}_style", "").strip()
            ]
            rows[row["prompt_id"].strip()] = GroundTruth(
                prompt_id=row["prompt_id"].strip(),
                building_type=row.get("building_type", "").strip(),
                main_style=row["main_style"].strip(),
                distractor_styles=distractors,
            )
    return rows


def _load_subset(path: Path) -> List[tuple]:
    """Read a diagnostic-subset CSV into a list of (prompt_id, generator, group).

    The CSV is produced by ``oracle_matrix.py --export-subset`` and selects only
    the diagnostic images (broken + hard + guard), so the eval replays ~95 images
    instead of the full 200 — cheaper and targeted at where the system loses.
    """
    entries: List[tuple] = []
    with path.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            pid = row["prompt_id"].strip()
            gen = row["generator"].strip().lower()
            group = row.get("group", "").strip()
            if pid and gen:
                entries.append((pid, gen, group))
    return entries


def _kb_id(kb, name: str) -> Optional[str]:
    """Resolve a free-text style name to its KB id (None if unmatched)."""
    entry = kb.match(name)
    return entry.id if entry else None


def _top_n_styles(result: FinalAnalysisResult, n: int) -> List[str]:
    """Return the top-n style names from the final mixture (or the single label)."""
    if result.style_distribution is not None:
        ranked = sorted(
            result.style_distribution.distribution.items(),
            key=lambda kv: kv[1],
            reverse=True,
        )
        return [name for name, _ in ranked[:n]]
    return [result.style] if result.style else []


def _score(kb, gt: GroundTruth, result: FinalAnalysisResult,
           generator: str, group: str = "") -> EvalRow:
    """Compare one pipeline result against the ground truth, on KB ids."""
    gt_id = _kb_id(kb, gt.main_style)
    pred_id = _kb_id(kb, result.style)

    candidate_ids = {cid for n in result.candidate_names if (cid := _kb_id(kb, n))}
    recall_hit = gt_id is not None and gt_id in candidate_ids

    top1_hit = gt_id is not None and pred_id == gt_id
    top3_ids = {cid for s in _top_n_styles(result, 3) if (cid := _kb_id(kb, s))}
    top3_hit = gt_id is not None and gt_id in top3_ids

    gt_entry = kb.get(gt_id) if gt_id else None
    pred_entry = kb.get(pred_id) if pred_id else None
    family_hit = bool(
        gt_entry and pred_entry and gt_entry.parent
        and gt_entry.parent == pred_entry.parent
    )

    distractor_ids = {cid for s in gt.distractor_styles if (cid := _kb_id(kb, s))}
    distractor_hit = pred_id is not None and pred_id in distractor_ids

    return EvalRow(
        prompt_id=gt.prompt_id,
        generator=generator,
        gt_style=gt.main_style,
        pred_style=result.style,
        recall_hit=recall_hit,
        top1_hit=top1_hit,
        top3_hit=top3_hit,
        family_hit=family_hit,
        distractor_hit=distractor_hit,
        uncertain=result.uncertain,
        panel_agreement=result.panel_agreement,
        n_candidates=len(result.candidate_names),
        group=group,
    )


async def _eval_one(orch: AnalysisOrchestrator, kb, gt: GroundTruth,
                    generator: str, image_path: Path,
                    sem: asyncio.Semaphore, group: str = "") -> EvalRow:
    """Analyse one image and score it; capture any failure as an error row."""
    async with sem:
        try:
            image_bytes = image_path.read_bytes()
            result = await orch.analyze(image_bytes)
            # A result with NO candidates means Stage A/B produced nothing —
            # almost always an upstream API/quota failure, not a real prediction.
            # Count it as an ERROR (excluded from metrics) instead of a wrong
            # answer, otherwise a partial/quota-limited run silently pollutes the
            # aggregates (e.g. counting unanalysed images as recall misses).
            if not result.candidate_names:
                print(f"  [{generator:7}] id={gt.prompt_id:>3} ERROR: "
                      "no candidates (likely API/quota failure)")
                return EvalRow(
                    prompt_id=gt.prompt_id, generator=generator,
                    gt_style=gt.main_style, pred_style="", recall_hit=False,
                    top1_hit=False, top3_hit=False, family_hit=False,
                    distractor_hit=False, uncertain=True, panel_agreement=None,
                    n_candidates=0, error="no_candidates", group=group,
                )
            row = _score(kb, gt, result, generator, group)
            flag = "✗"
            if row.top1_hit:
                flag = "✓"
            elif row.recall_hit:
                flag = "~"  # right style was available but not chosen
            print(f"  [{generator:7}] id={gt.prompt_id:>3} {flag} "
                  f"gt={gt.main_style[:24]:24} pred={row.pred_style[:24]:24} "
                  f"recall={'Y' if row.recall_hit else 'n'} "
                  f"agree={row.panel_agreement}")
            return row
        except Exception as exc:  # noqa: BLE001 — boundary: keep the sweep going
            print(f"  [{generator:7}] id={gt.prompt_id:>3} ERROR: {exc}")
            return EvalRow(
                prompt_id=gt.prompt_id, generator=generator,
                gt_style=gt.main_style, pred_style="", recall_hit=False,
                top1_hit=False, top3_hit=False, family_hit=False,
                distractor_hit=False, uncertain=True, panel_agreement=None,
                n_candidates=0, error=str(exc), group=group,
            )


def _pct(n: int, d: int) -> str:
    """Format a fraction as 'count/total (xx.x%)'."""
    return f"{n}/{d} ({100.0 * n / d:.1f}%)" if d else "0/0 (n/a)"


def _print_summary(rows: List[EvalRow]) -> None:
    """Print the aggregate metrics + a risk-coverage sweep."""
    scored = [r for r in rows if not r.error and r.n_candidates > 0]
    n = len(scored)
    errors = len(rows) - n
    print("\n" + "=" * 72)
    print(f"RESULTS  ({n} scored, {errors} errors, {len(rows)} total)")
    print("=" * 72)
    if not n:
        print("No scored images.")
        return

    recall = sum(r.recall_hit for r in scored)
    top1 = sum(r.top1_hit for r in scored)
    top3 = sum(r.top3_hit for r in scored)
    family = sum(r.family_hit for r in scored)
    distractor = sum(r.distractor_hit for r in scored)
    uncertain = sum(r.uncertain for r in scored)

    print(f"candidate_recall@K : {_pct(recall, n)}   <- HARD CEILING (Stage A/B)")
    print(f"top-1 accuracy     : {_pct(top1, n)}")
    print(f"top-3 accuracy     : {_pct(top3, n)}")
    print(f"family accuracy    : {_pct(family, n)}")
    print(f"distractor rate    : {_pct(distractor, n)}   (lower is better)")
    print(f"abstained          : {_pct(uncertain, n)}")

    # Of the recall hits, how many did the panel actually convert to top-1?
    converted = sum(r.top1_hit for r in scored if r.recall_hit)
    print(f"\nconversion (top-1 | recall hit): {_pct(converted, recall)}"
          "   <- judging quality once the style is available")
    lost_pre_panel = n - recall
    print(f"lost before the panel (recall miss): {_pct(lost_pre_panel, n)}")

    # Risk-coverage: sweep an abstention threshold on panel_agreement.
    print("\nrisk-coverage (abstain when panel_agreement < t):")
    print(f"  {'t':>5} {'coverage':>18} {'selective top-1':>22}")
    have_agree = [r for r in scored if r.panel_agreement is not None]
    for t in _RISK_THRESHOLDS:
        kept = [r for r in have_agree if r.panel_agreement >= t]
        sel_top1 = sum(r.top1_hit for r in kept)
        cov = _pct(len(kept), n)
        sel = _pct(sel_top1, len(kept)) if kept else "n/a"
        print(f"  {t:>5.1f} {cov:>18} {sel:>22}")

    # Per-generator breakdown.
    print("\nby generator:")
    for gen in sorted({r.generator for r in scored}):
        g = [r for r in scored if r.generator == gen]
        print(f"  {gen:8} recall={_pct(sum(r.recall_hit for r in g), len(g))}"
              f"  top1={_pct(sum(r.top1_hit for r in g), len(g))}")

    # Per-group breakdown (diagnostic subset only). The key delta view: how many
    # of the 43 BROKEN images are now recovered, how the HARD set does, and
    # whether the GUARD set (currently-correct) regressed.
    groups = [g for g in ("broken", "hard", "guard") if any(r.group == g for r in scored)]
    if groups:
        print("\nby diagnostic group (target: broken top-1 UP, guard top-1 NOT down):")
        for grp in groups:
            g = [r for r in scored if r.group == grp]
            print(f"  {grp:7} top1={_pct(sum(r.top1_hit for r in g), len(g))}"
                  f"  recall={_pct(sum(r.recall_hit for r in g), len(g))}"
                  f"  abstain={_pct(sum(r.uncertain for r in g), len(g))}")


def _open_output(out_path: Path, resume: bool) -> tuple:
    """Open the output CSV for incremental writing.

    Returns ``(file_handle, csv_writer, preloaded_rows, done_pairs)``. When
    ``resume`` is set and the file already exists, the previously written GOOD
    rows (no error, at least one candidate) are kept and their (prompt_id,
    generator) pairs are returned so the caller can skip re-analysing them;
    rows that errored out (e.g. a quota failure) are dropped and will be retried.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    preloaded: List[EvalRow] = []
    if resume and out_path.exists():
        preloaded = [
            r for r in _read_existing_rows(out_path)
            if not r.error and r.n_candidates > 0
        ]
    done = {(r.prompt_id, r.generator) for r in preloaded}
    fh = out_path.open("w", newline="", encoding="utf-8")
    writer = csv.writer(fh)
    writer.writerow(_CSV_HEADER)
    for r in preloaded:
        writer.writerow(_row_values(r))
    fh.flush()
    return fh, writer, preloaded, done


async def _run(args: argparse.Namespace) -> int:
    """Drive the evaluation sweep and print/write the results."""
    if not is_pipeline_configured():
        print("ERROR: set GEMINI_API_KEY, DEEPSEEK_API_KEY, OPENAI_API_KEY in .env")
        return 1

    # Translation is irrelevant to every metric; turn it off to save two calls.
    settings.ENABLE_BILINGUAL = False
    if args.decision_mode:
        settings.DECISION_MODE = args.decision_mode

    ground_truth = _load_ground_truth()
    kb = get_style_kb()
    orch = AnalysisOrchestrator()

    out_fh, out_writer, preloaded, done = _open_output(Path(args.out), args.resume)
    if done:
        print(f"Resume: {len(done)} good images already in {Path(args.out).name}; "
              "skipping them (errored images will be retried).\n")
    write_lock = asyncio.Lock()

    async def _stream(coro):
        """Await a scored image and append it to the CSV as soon as it is ready."""
        row = await coro
        async with write_lock:
            out_writer.writerow(_row_values(row))
            out_fh.flush()
        return row

    sem = asyncio.Semaphore(args.workers)
    tasks = []

    if args.subset:
        # Targeted diagnostic replay: only the (prompt_id, generator) pairs listed
        # in the subset CSV (broken + hard + guard), each tagged with its group.
        subset = _load_subset(Path(args.subset))
        if args.limit:
            subset = subset[: args.limit]
        for pid, gen, group in subset:
            gt = ground_truth.get(pid)
            if gt is None or gen not in _DATA_DIRS:
                print(f"  [{gen:7}] id={pid:>3} SKIP (no ground truth / bad generator)")
                continue
            if (pid, gen) in done:
                continue
            image_path = _DATA_DIRS[gen] / f"{pid}.png"
            if not image_path.is_file():
                print(f"  [{gen:7}] id={pid:>3} SKIP (missing {image_path.name})")
                continue
            tasks.append(_stream(_eval_one(orch, kb, gt, gen, image_path, sem, group)))
    else:
        prompt_ids = sorted(ground_truth, key=lambda x: int(x))
        if args.limit:
            prompt_ids = prompt_ids[: args.limit]
        generators = [g.strip().lower() for g in args.generators.split(",") if g.strip()]
        for pid in prompt_ids:
            gt = ground_truth[pid]
            for gen in generators:
                if (pid, gen) in done:
                    continue
                image_path = _DATA_DIRS[gen] / f"{pid}.png"
                if not image_path.is_file():
                    print(f"  [{gen:7}] id={pid:>3} SKIP (missing {image_path.name})")
                    continue
                tasks.append(_stream(_eval_one(orch, kb, gt, gen, image_path, sem)))

    print(f"Evaluating {len(tasks)} images "
          f"(decision_mode={settings.DECISION_MODE}, top_k={settings.RETRIEVAL_TOP_K}, "
          f"min_votes={settings.EVIDENCE_MIN_VOTES}, workers={args.workers})...\n")
    start = time.monotonic()
    try:
        new_rows = list(await asyncio.gather(*tasks)) if tasks else []
    finally:
        out_fh.close()
    elapsed = time.monotonic() - start

    all_rows = preloaded + new_rows
    _print_summary(all_rows)
    print(f"\nTotal time: {elapsed:.0f}s "
          f"({elapsed / max(len(new_rows), 1):.1f}s/new image)")
    print(f"Per-image results written to {Path(args.out)} "
          f"({len(all_rows)} rows: {len(preloaded)} kept + {len(new_rows)} new)")
    return 0


def main() -> int:
    """Parse CLI args and run the evaluation."""
    parser = argparse.ArgumentParser(description="Open-vocab pipeline evaluation")
    parser.add_argument("--limit", type=int, default=0,
                        help="evaluate only the first N prompt ids (0 = all)")
    parser.add_argument("--generators", default="chatgpt,gemini",
                        help="comma list: chatgpt,gemini")
    parser.add_argument("--workers", type=int, default=3,
                        help="max concurrent image analyses")
    parser.add_argument("--subset", default="",
                        help="diagnostic subset CSV (from oracle_matrix.py "
                             "--export-subset): replay only those images")
    parser.add_argument("--decision-mode", default="",
                        choices=["", "arbiter", "panel", "consensus"],
                        help="override DECISION_MODE for this run (W1 A/B/C)")
    parser.add_argument("--out", default=str(_PROJECT_ROOT / "results" / "eval_baseline.csv"),
                        help="per-image results CSV path")
    parser.add_argument("--resume", action="store_true",
                        help="reuse an existing --out CSV: skip already-scored "
                             "images and only analyse the missing/errored ones")
    args = parser.parse_args()
    return asyncio.run(_run(args))


if __name__ == "__main__":
    raise SystemExit(main())
