"""Compute the oracle / agreement matrix from ThucNghiem.xlsx.

The workbook records, per image, whether each base model (Gemini, ChatGPT) and
the system got the style right (1) or wrong (0). One prompt row yields TWO
images — one generated by Gemini, one by ChatGPT — so 100 prompts → 200 images.

Per-image correctness columns (located by header text, so the script keeps
working if the layout shifts):

    ChatGPT-generated image          Gemini-generated image
    -----------------------          ----------------------
    Gemini   : "GEMINI phân tích CHAT"     "GEMINI phân tích GEMINI"
    ChatGPT  : "CHAT phân tích CHAT"       "CHAT phân tích GEMINI"
    System   : "HỆ THỐNG CHAT"             "HỆ THỐNG GEMINI"
    Grok*    : "GROK phân tích CHAT"       "GROK phân tích GEMINI"   (optional)

The 4-cell agreement matrix (both correct / only-Gemini / only-ChatGPT /
both-wrong) gives the ORACLE = number of images at least one base model got
right = the hard ceiling for any method that combines the two base models. It
also reports how many images the system DESTROYS (system wrong where ≥1 base
was right) versus ADDS (system right where both base were wrong) — the precise
value-add / value-loss diagnosis driving the redesign.

If the optional Grok columns are present, a 3-model oracle is also reported.

Usage (from project root):
    python scripts/oracle_matrix.py
    python scripts/oracle_matrix.py --xlsx ThucNghiem.xlsx
"""
from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import openpyxl

_PROJECT_ROOT = Path(__file__).resolve().parents[1]

# header text → internal key
_HEADERS = {
    "GEMINI phân tích CHAT": "gem_on_chat",
    "GEMINI phân tích GEMINI": "gem_on_gem",
    "CHAT phân tích GEMINI": "chat_on_gem",
    "CHAT phân tích CHAT": "chat_on_chat",
    "HỆ THỐNG CHAT": "sys_on_chat",
    "HỆ THỐNG GEMINI": "sys_on_gem",
    "GROK phân tích CHAT": "grok_on_chat",
    "GROK phân tích GEMINI": "grok_on_gem",
}


def _as_bit(value: object) -> Optional[int]:
    """Return 1/0 for a clean binary cell, else None (blank/non-numeric)."""
    try:
        return 1 if int(value) == 1 else 0  # type: ignore[arg-type]
    except (TypeError, ValueError):
        return None


def _find_columns(ws) -> Tuple[Optional[int], Dict[str, int]]:
    """Locate the STT column and every known result column by header text.

    Returns ``(stt_col, {key: col_index})`` with 1-based column indices; keys
    absent from the sheet are simply omitted from the dict.
    """
    stt_col: Optional[int] = None
    cols: Dict[str, int] = {}
    for r in range(1, 6):
        for c in range(1, ws.max_column + 1):
            val = ws.cell(row=r, column=c).value
            if not isinstance(val, str):
                continue
            text = val.strip()
            if text.upper() == "STT":
                stt_col = c
            elif text in _HEADERS:
                cols[_HEADERS[text]] = c
    return stt_col, cols


# Workbook suffix → evaluate_openvocab.py generator key (its data-dir name).
_GENERATOR = {"chat": "chatgpt", "gem": "gemini"}


def _collect_images(ws, stt_col: int, cols: Dict[str, int]) -> List[Dict[str, object]]:
    """Build one record per image: {prompt_id, generator, gem, chat, sys, (grok)}.

    ``prompt_id`` (= STT as a string) and ``generator`` ("chatgpt"/"gemini")
    identify the image file the eval harness loads
    (``data/{ChatGPT|Gemini}/{prompt_id}.png``), so a diagnostic subset exported
    here can be replayed by ``evaluate_openvocab.py --subset``. Skips an image if
    any required base/system bit is blank (never analysed).
    """
    have_grok = "grok_on_chat" in cols and "grok_on_gem" in cols
    images: List[Dict[str, object]] = []
    for r in range(1, ws.max_row + 1):
        stt = ws.cell(row=r, column=stt_col).value
        if not isinstance(stt, int):
            continue
        # ChatGPT-generated image, then Gemini-generated image
        for suffix in ("chat", "gem"):
            gem = _as_bit(ws.cell(row=r, column=cols[f"gem_on_{suffix}"]).value)
            chat = _as_bit(ws.cell(row=r, column=cols[f"chat_on_{suffix}"]).value)
            sysv = _as_bit(ws.cell(row=r, column=cols[f"sys_on_{suffix}"]).value)
            if None in (gem, chat, sysv):
                continue
            rec: Dict[str, object] = {
                "prompt_id": str(stt),
                "generator": _GENERATOR[suffix],
                "gem": gem,
                "chat": chat,
                "sys": sysv,
            }
            if have_grok:
                grok = _as_bit(ws.cell(row=r, column=cols[f"grok_on_{suffix}"]).value)
                if grok is not None:
                    rec["grok"] = grok
            images.append(rec)
    return images


def _pct(num: int, den: int) -> str:
    """Format ``num/den`` as a percentage string (guards den==0)."""
    return f"{num} ({num / den:.1%})" if den else f"{num} (n/a)"


def _group_of(rec: Dict[str, object]) -> Optional[str]:
    """Classify one image into the diagnostic subset group (priority order).

    - ``broken``: system wrong where ≥1 base model was right (the 43 — the
      primary improvement target for the panel-vs-arbiter redesign).
    - ``hard``  : both base models wrong (the recall / escape-hatch ceiling).
    - ``guard`` : everyone right (purest stable-correct pool) — sampled later to
      catch regressions when the decision logic changes.
    Returns None for images outside all three groups (not in the subset).
    """
    gem, chat, sysv = rec["gem"], rec["chat"], rec["sys"]
    if not sysv and (gem or chat):
        return "broken"
    if not gem and not chat:
        return "hard"
    if sysv and gem and chat:
        return "guard"
    return None


def _export_subset(
    images: List[Dict[str, object]], out_path: Path, guard_n: int, seed: int
) -> None:
    """Write the 3-group diagnostic subset (broken + hard + sampled guard) to CSV.

    All ``broken`` and ``hard`` images are kept; ``guard`` is a deterministic
    random sample of ``guard_n`` stable-correct images (reproducible via
    ``seed``). Columns: ``prompt_id, generator, group`` — consumed by
    ``evaluate_openvocab.py --subset``.
    """
    import csv
    import random

    broken = [r for r in images if _group_of(r) == "broken"]
    hard = [r for r in images if _group_of(r) == "hard"]
    guard_pool = [r for r in images if _group_of(r) == "guard"]
    rng = random.Random(seed)
    guard = rng.sample(guard_pool, min(guard_n, len(guard_pool)))

    rows = (
        [(r, "broken") for r in broken]
        + [(r, "hard") for r in hard]
        + [(r, "guard") for r in guard]
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(["prompt_id", "generator", "group"])
        for rec, group in rows:
            writer.writerow([rec["prompt_id"], rec["generator"], group])
    print(
        f"\nDiagnostic subset written to {out_path}: "
        f"{len(broken)} broken + {len(hard)} hard + {len(guard)} guard "
        f"(of {len(guard_pool)} stable-correct) = {len(rows)} images"
    )


def _report(images: List[Dict[str, object]]) -> None:
    """Print the agreement matrix, oracle, and system value-add/loss."""
    n = len(images)
    gem = sum(i["gem"] for i in images)
    chat = sum(i["chat"] for i in images)
    syst = sum(i["sys"] for i in images)

    both = sum(1 for i in images if i["gem"] and i["chat"])
    only_g = sum(1 for i in images if i["gem"] and not i["chat"])
    only_c = sum(1 for i in images if i["chat"] and not i["gem"])
    both_wrong = sum(1 for i in images if not i["gem"] and not i["chat"])
    oracle2 = n - both_wrong

    sys_added = sum(1 for i in images if i["sys"] and not i["gem"] and not i["chat"])
    sys_lost = sum(1 for i in images if not i["sys"] and (i["gem"] or i["chat"]))

    print(f"Images: {n}")
    print(f"  Gemini base : {_pct(gem, n)}")
    print(f"  ChatGPT base: {_pct(chat, n)}")
    print(f"  System      : {_pct(syst, n)}")
    print("--- 4-cell agreement (2 base models) ---")
    print(f"  both correct : {both}")
    print(f"  only Gemini  : {only_g}")
    print(f"  only ChatGPT : {only_c}")
    print(f"  both wrong   : {both_wrong}")
    print("--- headroom (2 model) ---")
    print(f"  ORACLE (>=1 base correct) = {_pct(oracle2, n)}  [hard ceiling for any 2-model combiner]")
    print(f"  best single base          = {_pct(max(gem, chat), n)}")
    print(f"  disagreement cases (exactly 1 base right) = {only_g + only_c}")
    print(f"  system ADDS  (right where both base wrong)   = {sys_added}")
    print(f"  system LOSES (wrong where >=1 base right)     = {sys_lost}")

    if all("grok" in i for i in images) and images:
        grok = sum(i["grok"] for i in images)
        all_wrong3 = sum(
            1 for i in images if not i["gem"] and not i["chat"] and not i["grok"]
        )
        oracle3 = n - all_wrong3
        print("--- headroom (3 model, with Grok) ---")
        print(f"  Grok base : {_pct(grok, n)}")
        print(f"  all-3-wrong = {all_wrong3}")
        print(f"  ORACLE (>=1 of 3 correct) = {_pct(oracle3, n)}  [new ceiling — may exceed 2-model oracle]")


def main() -> int:
    """Load ThucNghiem.xlsx and print the oracle / agreement diagnosis."""
    parser = argparse.ArgumentParser(description="Oracle matrix from ThucNghiem.xlsx")
    parser.add_argument("--xlsx", default=str(_PROJECT_ROOT / "ThucNghiem.xlsx"))
    parser.add_argument(
        "--export-subset", default="",
        help="write the diagnostic subset (broken+hard+guard) to this CSV path",
    )
    parser.add_argument(
        "--guard", type=int, default=25,
        help="number of stable-correct guard images to sample (default 25)",
    )
    parser.add_argument(
        "--seed", type=int, default=42, help="random seed for guard sampling",
    )
    args = parser.parse_args()

    xlsx_path = Path(args.xlsx)
    if not xlsx_path.is_file():
        print(f"ERROR: workbook not found: {xlsx_path}")
        return 1

    wb = openpyxl.load_workbook(xlsx_path, read_only=True, data_only=True)
    ws = wb.active
    stt_col, cols = _find_columns(ws)
    required = ["gem_on_chat", "gem_on_gem", "chat_on_chat", "chat_on_gem",
                "sys_on_chat", "sys_on_gem"]
    missing = [k for k in required if k not in cols]
    if stt_col is None or missing:
        print(f"ERROR: missing columns (STT={stt_col}, missing keys={missing})")
        return 1

    images = _collect_images(ws, stt_col, cols)
    if not images:
        print("ERROR: no fully-scored images found.")
        return 1
    _report(images)
    if args.export_subset:
        _export_subset(images, Path(args.export_subset), args.guard, args.seed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
